"""Auther Column in Books changed

Revision ID: 1c3460bc6d0e
Revises: 757adde07a49
Create Date: 2024-01-06 12:21:14.221298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c3460bc6d0e'
down_revision: Union[str, None] = '757adde07a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('auther', sa.String(), nullable=False))
    op.drop_column('books', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('books', 'auther')
    # ### end Alembic commands ###
