"""Foriegn Key constrait added

Revision ID: cf2c248b2211
Revises: 36fd96c07cdd
Create Date: 2024-01-07 11:40:49.241713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2c248b2211'
down_revision: Union[str, None] = '36fd96c07cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('auther_id', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('publisher_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'books', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'books', 'publisher', ['publisher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'books', 'auther', ['auther_id'], ['id'], ondelete='CASCADE')
    op.drop_column('books', 'publisher')
    op.drop_column('books', 'auther')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('auther', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('publisher', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'publisher_id')
    op.drop_column('books', 'auther_id')
    op.drop_column('books', 'owner_id')
    # ### end Alembic commands ###
