"""Foreign keys removed

Revision ID: f53a40baa390
Revises: 2c5cab4f9084
Create Date: 2024-01-06 20:56:53.000009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53a40baa390'
down_revision: Union[str, None] = '2c5cab4f9084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_publisher_id_fkey', 'books', type_='foreignkey')
    op.drop_constraint('books_author_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'publisher_id')
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('publisher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('books_author_id_fkey', 'books', 'auther', ['author_id'], ['id'])
    op.create_foreign_key('books_publisher_id_fkey', 'books', 'publisher', ['publisher_id'], ['id'])
    # ### end Alembic commands ###
